name: CI/CD for OLAPify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres sqlfluff

  dbt-validate:
    name: Validate dbt Models
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres

      - name: Set up dbt profiles
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES }}" > ~/.dbt/profiles.yml

      - name: Test dbt Compilation
        run: |
          dbt deps
          dbt compile --profiles-dir ~/.dbt

      - name: Run dbt Tests
        run: |
          dbt test --profiles-dir ~/.dbt

  lint-sql:
    name: Lint SQL Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sqlfluff
        run: pip install sqlfluff

      - name: Lint SQL files
        run: |
          sqlfluff lint northwind_model --dialect postgres
          sqlfluff fix northwind_model --dialect postgres --force

  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: [dbt-validate, lint-sql]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Start Docker Compose
        run: |
          docker-compose down
          docker-compose up -d --build

      - name: Run dbt Models in Production
        run: |
          dbt run --profiles-dir ~/.dbt
